# Generated by Django 5.2.7 on 2025-10-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        ('consumers', '0002_consumerrouteassignmenthistory_consumer_name_and_more'),
        ('lookups', '0001_initial'),
        ('products', '0002_productvariant_products_pr_product_4952c7_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='connectiondetails',
            index=models.Index(fields=['consumer', 'connection_type'], name='connections_consume_ebbe94_idx'),
        ),
        migrations.AddIndex(
            model_name='connectiondetails',
            index=models.Index(fields=['sv_date'], name='connections_sv_date_ae9746_idx'),
        ),
        migrations.AddIndex(
            model_name='connectiondetails',
            index=models.Index(fields=['product'], name='connections_product_a74db2_idx'),
        ),
    ]
