# Generated by Django 5.2.7 on 2025-10-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRouteAssignment',
            fields=[
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='delivery_assignment', serialize=False, to='routes.route')),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_assignments', to='delivery.deliveryperson')),
            ],
            options={
                'verbose_name': 'Delivery Route Assignment',
                'verbose_name_plural': 'Delivery Route Assignments',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRouteAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='delivery.deliveryperson')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='routes.route')),
            ],
            options={
                'verbose_name': 'Delivery Route Assignment History',
                'verbose_name_plural': 'Delivery Route Assignment History',
                'ordering': ['-timestamp'],
            },
        ),
    ]
