# Generated by Django 5.2.7 on 2025-10-20 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrouteassignmenthistory',
            name='delivery_person_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='deliveryrouteassignmenthistory',
            name='route_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deliveryrouteassignmenthistory',
            name='route_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='deliveryrouteassignmenthistory',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='delivery.deliveryperson'),
        ),
        migrations.AlterField(
            model_name='deliveryrouteassignmenthistory',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='routes.route'),
        ),
    ]
