# Generated by Django 5.2.7 on 2025-10-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryrouteassignmenthistory_delivery_person_name_and_more'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deliveryperson',
            index=models.Index(fields=['name'], name='delivery_de_name_c5d7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrouteassignment',
            index=models.Index(fields=['delivery_person'], name='delivery_de_deliver_1e3d1f_idx'),
        ),
    ]
