# Generated by Django 5.2.7 on 2025-10-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LGDInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.IntegerField(verbose_name='LGD District Code')),
                ('district_name', models.CharField(max_length=100, verbose_name='District Name')),
                ('sub_district', models.IntegerField(verbose_name='LGD Sub-District Code')),
                ('sub_district_name', models.CharField(max_length=100, verbose_name='Sub-District Name')),
                ('village', models.IntegerField(verbose_name='LGD Village Code')),
                ('village_name', models.CharField(max_length=100, verbose_name='Village Name')),
            ],
            options={
                'verbose_name': 'LGD Information',
                'verbose_name_plural': 'LGD Information',
            },
        ),
    ]
