# Generated by Django 5.2.7 on 2025-10-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgd', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lgdinfo',
            index=models.Index(fields=['district', 'sub_district', 'village'], name='lgd_lgdinfo_distric_59e2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='lgdinfo',
            index=models.Index(fields=['district_name'], name='lgd_lgdinfo_distric_6665f2_idx'),
        ),
        migrations.AddIndex(
            model_name='lgdinfo',
            index=models.Index(fields=['village_name'], name='lgd_lgdinfo_village_e2f77a_idx'),
        ),
    ]
