# Generated by Django 5.2.7 on 2025-10-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=50, unique=True, verbose_name='Unique route code')),
                ('area_code_description', models.CharField(max_length=150, verbose_name='Route description')),
            ],
        ),
        migrations.CreateModel(
            name='RouteArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, verbose_name='Area name')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='routes.route', verbose_name='Associated route')),
            ],
        ),
    ]
