# Generated by Django 5.2.7 on 2025-10-22 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routearea',
            options={'ordering': ['area_name'], 'verbose_name': 'Route Area', 'verbose_name_plural': 'Route Areas'},
        ),
        migrations.AlterField(
            model_name='routearea',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='routes.route', verbose_name='Associated route'),
        ),
    ]
