# Generated by Django 5.2.7 on 2025-10-20 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterField(
            model_name='address',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['content_type', 'object_id'], name='address_add_content_c8c3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['content_type', 'object_id'], name='address_con_content_4df061_idx'),
        ),
    ]
