# Generated by Django 5.2.7 on 2025-10-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_options_alter_contact_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['pin_code'], name='address_add_pin_cod_0aff1d_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city_town_village'], name='address_add_city_to_e59f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['mobile_number'], name='address_con_mobile__c85ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='address_con_email_d2f0e2_idx'),
        ),
    ]
