# Generated by Django 5.2.7 on 2025-10-20 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerrouteassignmenthistory',
            name='consumer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consumerrouteassignmenthistory',
            name='consumer_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consumerrouteassignmenthistory',
            name='route_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consumerrouteassignmenthistory',
            name='route_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='consumerrouteassignmenthistory',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='consumers.consumer'),
        ),
        migrations.AlterField(
            model_name='consumerrouteassignmenthistory',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='routes.route'),
        ),
        migrations.AddIndex(
            model_name='consumerrouteassignmenthistory',
            index=models.Index(fields=['-timestamp'], name='consumers_c_timesta_bee9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerrouteassignmenthistory',
            index=models.Index(fields=['consumer', 'timestamp'], name='consumers_c_consume_4d334b_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerrouteassignmenthistory',
            index=models.Index(fields=['route', 'timestamp'], name='consumers_c_route_i_65acf7_idx'),
        ),
    ]
