# Generated by Django 5.2.7 on 2025-10-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_consumerrouteassignmenthistory_consumer_name_and_more'),
        ('lookups', '0001_initial'),
        ('routes', '0001_initial'),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['consumer_name'], name='consumers_c_consume_a9103d_idx'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['opting_status'], name='consumers_c_opting__9c0e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['is_kyc_done'], name='consumers_c_is_kyc__06ac37_idx'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['category', 'consumer_type'], name='consumers_c_categor_86f3df_idx'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['scheme'], name='consumers_c_scheme__ae5229_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerrouteassignment',
            index=models.Index(fields=['route'], name='consumers_c_route_i_36eb32_idx'),
        ),
    ]
