# Generated by Django 5.2.7 on 2025-10-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Product category name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Category description')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='Unit name (e.g., kg, pcs)')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description of the unit')),
            ],
            options={
                'verbose_name': 'Unit of Measurement',
                'verbose_name_plural': 'Units of Measurement',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='Product code / SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Variant name')),
                ('size', models.DecimalField(decimal_places=2, help_text='The numeric size, like 14.2 or 19.0', max_digits=10, verbose_name='Size (e.g., weight or volume)')),
                ('variant_type', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.product', verbose_name='Parent product category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.unit', verbose_name='Unit of measurement')),
            ],
            options={
                'unique_together': {('product', 'name')},
            },
        ),
    ]
