# Generated by Django 5.2.7 on 2025-10-25 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_products_pr_product_4952c7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price before the change', max_digits=10, null=True, verbose_name='Previous price')),
                ('new_price', models.DecimalField(decimal_places=2, help_text='Price after the change', max_digits=10, verbose_name='New price')),
                ('price_change', models.DecimalField(decimal_places=2, help_text='Difference (new - old)', max_digits=10, verbose_name='Price change amount')),
                ('price_change_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change', max_digits=6, null=True, verbose_name='Price change %')),
                ('effective_date', models.DateTimeField(auto_now_add=True, help_text='When this price became effective', verbose_name='Effective date')),
                ('reason', models.CharField(blank=True, help_text='Optional reason for price change', max_length=200, verbose_name='Reason for change')),
                ('notes', models.TextField(blank=True, help_text='Any additional information', verbose_name='Additional notes')),
            ],
            options={
                'verbose_name': 'Product Variant Price History',
                'verbose_name_plural': 'Product Variant Price History',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current price for this variant', max_digits=10, verbose_name='Current selling price'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['price'], name='products_pr_price_a59bc5_idx'),
        ),
        migrations.AddField(
            model_name='productvariantpricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed by'),
        ),
        migrations.AddField(
            model_name='productvariantpricehistory',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.productvariant', verbose_name='Product variant'),
        ),
        migrations.AddIndex(
            model_name='productvariantpricehistory',
            index=models.Index(fields=['-effective_date'], name='products_pr_effecti_7b2754_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantpricehistory',
            index=models.Index(fields=['variant', '-effective_date'], name='products_pr_variant_1ede9e_idx'),
        ),
    ]
